monprojet/factures/urls.py
from django.urls import path
from . import views

    
urlpatterns = [
   path('creer_facture/',views.creer_facture, name='creer_facture'),
  path('afficher_facture/<int:facture_id>/',views.afficher_facture, name='afficher_facture'),
 path('facture/ajouter_medicament/<int:facture_id>/', views.ajouter_medicament, name='ajouter_medicament'),

  path('facture/imprimer/<int:facture_id>/', views.imprimer_facture, name='imprimer_facture'),

    
]
   

monprojet/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index, name = 'index'),
    path('menu', views.menu, name = 'menu'),


]

monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
     path('',include('gventes.urls')),
    path('',include('home.urls')),
    path('',include('gststock.urls')),
    path('',include('gfournisseur.urls')),
    path('',include('client.urls')),
    path('',include('utilisateur.urls')),
    path('',include('gcommande.urls')),
    path('',include('factures.urls')),





]

monprojet/factures/models.py
from datetime import date
from django.db import models
from client.models import patients
from gststock.models import medicament


class Facture(models.Model):
    patient = models.ForeignKey(patients, on_delete=models.CASCADE, null=True)
  
    date_facture =models.DateField(default= date.today)
    imprimee = models.BooleanField(default=False)
    annulee = models.BooleanField(default=False)


    def __str__(self):
        return f"Facture #{self.id}"


class MedicamentsFacture(models.Model):
    facture = models.ForeignKey(Facture, on_delete=models.CASCADE,null=True)
    medicament = models.ForeignKey(medicament, on_delete=models.CASCADE,null=True)
    quantite_demandee = models.IntegerField()


    def __str__(self):
        return f"MedicamentFacture #{self.id}"

monprojet/factures/views.py
from django.shortcuts import render, redirect

from .models import medicament, Facture, MedicamentsFacture,patients
from django.db.models import F



def creer_facture(request):

    pats = patients.objects.all()
    meds = medicament.objects.all()

    if request.method == 'POST':
        patient_id = request.POST.get('patient')
        date_facture= request.POST.get('date_facture')


        patient = patients.objects.get(pk=patient_id)
        facture = Facture.objects.create(patient=patient,date_facture=date_facture)

        medicament_id = request.POST.get('medicament')
        prix_vente = request.POST.get('prix_vente')

        quantite_stock = medicament.objects.get(pk=medicament_id).qte
        quantite_demandee = int(request.POST.get('quantite_demandee'))

        medicament_commande = MedicamentsFacture.objects.create(facture=facture,
                                                                medicament_id=medicament_id,
                                                                quantite_demandee=quantite_demandee,
                                                                )
        prix_total = float(prix_vente) * float( quantite_demandee)


        index = 1
        medicament_list = []  # Liste pour stocker les informations des médicaments supplémentaires
           
         #  
        while True:
            medicament_id = request.POST.get(f'medicament_{index}')

            if not medicament_id:
                break

            quantite_demandee = int(request.POST.get(f'quantite_demandee_{index}'))
            medicaments = medicament.objects.get(pk=medicament_id)

            medicament_facture = MedicamentsFacture.objects.create(facture=facture,
                                                            medicaments=medicaments,
                                                            quantite_demandee=quantite_demandee,
                                                            )

            medicament_list.append(medicament_commande)  # Ajouter l'objet MedicamentCommande à la liste


           
           
           
           
         #  
            index += 1

        return redirect('afficher_facture', facture_id=facture.id)

    return render(request, 'factures/creer_facture.html', { 'meds': meds,'pats':pats,})


#
def afficher_facture(request, facture_id):
    facture = Facture.objects.get(pk=facture_id)
    medicaments_facture = MedicamentsFacture.objects.filter(facture=facture)
    medicament_list = []  # Liste pour stocker les médicaments supplémentaires

    # Calculer le prix total pour chaque médicament facturé
    for medicament_facture in medicaments_facture:
        medicament_facture.prix_total = medicament_facture.medicament.prix_vente * medicament_facture.quantite_demandee

    # Récupérer les informations des médicaments supplémentaires
    medicament_factures_supplementaires = MedicamentsFacture.objects.filter(facture=facture).exclude(id__in=medicaments_facture.values_list('id', flat=True))

    for medicament_facture in medicament_factures_supplementaires:
        medicament = medicament_facture.medicament
        quantite_demandee = medicament_facture.quantite_demandee

        medicament_info = {
            'medicament': medicament,
            'quantite_demandee': quantite_demandee,

        }
        medicament_list.append(medicament_info)

    total_prix = sum(medicament_facture.prix_total for medicament_facture in medicaments_facture)  # Calculer le prix total de la facture

    # annuler facture
    facture = Facture.objects.get(pk=facture_id)
    
    if request.method == 'POST' and 'annuler_facture' in request.POST:
        facture.annulee = True
        facture.save()
        return redirect('afficher_facture', facture_id=facture.id)
    


    return render(request,'factures/afficher_facture.html', {
        'facture': facture,
        'medicaments_facture': medicaments_facture,
        'medicament_list': medicament_list,
        'total_prix': total_prix,
    })
###

###

def ajouter_medicament(request, facture_id):
    facture = Facture.objects.get(pk=facture_id)
    medicaments_facture = MedicamentsFacture.objects.filter(facture=facture)

    if request.method == 'POST':
        medicament_id = request.POST.get('medicament')
        quantite_stock = medicament.objects.get(pk=medicament_id).qte
        quantite_demandee = int(request.POST.get('quantite_demandee'))

        medicament_facture = MedicamentsFacture.objects.create(facture=facture,
                                                                medicament_id=medicament_id,
                                                                quantite_demandee=quantite_demandee,
                                                                )

        return redirect('afficher_facture', facture_id=facture.id)

    meds = medicament.objects.all()
    return render(request, 'factures/ajouter_medicament.html', {'facture': facture, 'meds': meds})

from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa
from io import BytesIO


def imprimer_facture(request, facture_id):
    facture =Facture.objects.get(pk=facture_id)

###

    # Calculer le prix total pour chaque médicament facturé
    medicaments_facture = MedicamentsFacture.objects.filter(facture=facture)
    for medicament_facture in medicaments_facture:
        medicament_facture.prix_total = medicament_facture.medicament.prix_vente * medicament_facture.quantite_demandee


    # Calculer le prix total de la facture
    total_prix = sum(medicament_facture.prix_total for medicament_facture in medicaments_facture)

    


###
    # Récupérez les informations nécessaires pour générer le contenu de l'impression
    context = {
        'facture': facture,
        'medicaments_facture': medicaments_facture,
        'medicament_list': MedicamentsFacture.objects.filter(facture=facture).exclude(id__in=medicaments_facture.values_list('id', flat=True)),
        'total_prix': total_prix,
     }

    # Chargez le template d'impression
    template = get_template('factures/imprimer_facture.html')
    content = template.render(context)

    # Créez un flux de données pour stocker le résultat PDF
    pdf_file = BytesIO()

    # Convertissez le contenu HTML en PDF
    pisa.CreatePDF(content, dest=pdf_file)

    # Récupérez le contenu du fichier PDF à partir du flux de données
    pdf = pdf_file.getvalue()

    # Fermez le flux de données
    pdf_file.close()

    # Créez une réponse HTTP avec le contenu du PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="facture.pdf"'

    # Écrivez le contenu PDF dans la réponse HTTP
    response.write(pdf)

    return response
   

monprojet/templates/factures/afficher_facture.html
{% load static%}

{% include 'parties/nav.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
       
 p span{color: #3baea0;
 font-size: large;
}
    *{padding: 0;
    margin: 0;
box-sizing: border-box;
font-family: 'Poppins',sans-serif;}
body{
min-height: 100vh;
}
a{text-decoration: none;}
li{list-style: none;}

h1,h2{color: #444;}


.container{
position: absolute;
right: 0;
width: 80vw;
height: 100vh;
background: #f1f1f1;
}
.container .header{
position: fixed;
top: 0;
right: 0;
width: 80vw;
height: 10vh;
background: white;
display: flex;
align-items: center;
justify-content: center;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
z-index: 1;

}
.container .header .nav{width: 90%;
display: flex;
align-items: center;
}
.container .header .nav .search{
flex: 3;
display: flex;
justify-content: center;
}
.container .header .nav .search button{
width: 40px;
height: 40px;
border: none;
display: flex;
align-items: center;
justify-content: center;}
.container .header .nav .search button img{
width: 30px;
height: 30px;
}



.container .header .nav .user .img-case {
position: relative; 
width: 50px;
height: 50px;
}
.container .header .nav .user .img-case img{
position: absolute; 
top: 0;
left: 0;
width: 100%;

}
.btn{

background-color: #3baea0;
color: white;
padding: 5px 10px;
text-align: center;

}
.btn:hover{

color: #3baea0;
background: rgb(255, 255, 255);
padding: 3px 8px;
border: 2px solid #3baea0;

}
.container .content{
position: relative;
margin-top: 10vh;
min-height: 90vh;
background: #f1f1f1;
}
.container .content .cards{
padding: 10px 15px;
display: flex;
align-items: center;
justify-content: space-between;
flex-wrap: wrap;
justify-content: center;}
.container .content .cards .card{
width: 800px;
height: 150px;
background: white;
display: flex;
justify-content: space-around;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
text-align: center;
}
.annuler{margin-top: 5px;
  margin-bottom: 5px;
}
 .card2{
width: 300px;
height: 50px;
background: white;
margin: 0px 10px ;
display: flex;
align-items: center;
justify-content: space-around;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
font-size: 18px;
color: #3baea0;
border: 2px solid #3baea0;}
h3{color: #999;}
.container .content .content-2{
min-height: 60vh;
display: flex;
justify-content: space-around;
align-items: flex-start;
flex-wrap: wrap;
}
.container .content .content-2 .recent-payments{
min-height: 40vh;
width: 800px;
background: white;
margin: 0 25px 0px 25px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;
}




.title{
display: flex;
align-items: center;
justify-content: space-around;
padding: 15px 10px;
border-bottom: 2px solid #999;
}
.side-menu li img{width: 30px;height: 30px;}
table{
padding: 10px;
}
th,td{text-align: left;
padding: 8px;
}
.container .content .content-2 .recent-students table td:nth-child(1) img {
width: 40px;
height: 40px;
}

.commande h1{color: lightcoral;
padding: 10px 0 0 0px;
text-align: center;
}
.pc {background: lightcoral;
padding: 10px;}
.annuler{display: flex;
justify-content: center;}
@media screen and (max-width:536px) {

.container .content .cards {
justify-content: center;}}
</style>
</head>
<body>
  <div class="container">
    
<div class="content">
  <div class="commande">
  <h1>Facture Num: {{ facture.id }}</h1>
</div>
    <div class="cards">

        <div class="card">
            <div class="box">
             
              <div class="title">
              <h2>Informations sur la facture :</h2>
            </div>
            <br>
              <p><span> Client :</span> {{ facture.patient }}</p>
              <p><span>Date de facture:</span> {{ facture.date_facture }}</p>
              
            </div>
           
        </div>

       
     

    </div>
        <div class="content-2">
<div class="recent-payments">
    <div class="title">
      <h2>Médicaments inclus :</h2>

        <a href="{% url 'ajouter_medicament' facture_id=facture.id %}" class="btn">Ajouter medicament</a>
        
        
    </div>
    <table>
      <thead>
        <tr>
          <th>Nom médicament</th>
          <th>Quantité demandée</th>
          <th>Prix de vente</th>
          <th>Prix total</th>
        </tr>
      </thead>
      <tbody>
        {% for medicament_facture in medicaments_facture %}
          <tr>
            <td>{{ medicament_facture.medicament.designation }}</td>
            <td>{{ medicament_facture.quantite_demandee }}</td>
            <td>{{ medicament_facture.medicament.prix_vente }}</td>
            <td>{{ medicament_facture.prix_total }}</td>
          </tr>
        {% endfor %}
    
        {% for medicament_facture in medicament_list %}
          <tr>
            <td>{{ medicament_facture.medicament.designation }}</td>
            <td>{{ medicament_facture.quantite_demandee }}</td>
            <td>{{ medicament_facture.medicament.prix_vente }}</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr style="color: aqua;font-size: large;">
          <td colspan="3">Prix total</td>
          <td>{{ total_prix }}</td>
        </tr>
      </tfoot>
    </table>
    
    
</div>



<div class="annuler">
 
<a class="card2" href="{% url 'imprimer_facture' facture_id=facture.id %}" target="_blank">Imprimer</a>
{% if not facture.annulee %}
        <form method="post" action="">
            {% csrf_token %}
            <button class="card2" type="submit" name="annuler_facture">Annuler la facture</button>
        </form>
  {% else %}
        <p>La facture a été annulée.</p>
  {% endif %}

</div>  
  </div>
 
</div>



 </div> 
 







</body>
</html>
{% endblock content %}

monprojet/templates/factures/ajouter_medicament.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style> form {
    padding: 20px; 
}
h1{color: white;
}
body {
  background: linear-gradient(45deg, #ccc 0%, #ccc 50%, #3baea0 50%, #3baea0 100%);
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
}

label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

select, input[type="text"], input[type="number"],input[type="date"], textarea {
    width: 300px;
    margin-bottom: 10px;
    padding: 10px;


   

border: 1px solid #ccc;
border-radius: 4px;
}

option {font-size: 18px;}
textarea {
    height: 50px;
}

button[type="submit"] {
    padding: 10px 20px;
    background-color: #3baea0;
    color: white;
    border: none;
    cursor: pointer;
    
   
}form

/* Styles spécifiques aux éléments */
#id_adresse_fournisseur,
#id_qualite_fournisseur,
#quantite_stock {
    background-color: #f2f2f2;
    cursor: not-allowed;
}
.form ,h1 {display: flex;justify-content: center;}
form {display:inline;
float: left;
margin-right: 35px;
padding-right: 30px;
border: 1px solid #ccc;
            border-radius: 5px;
            background:white;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.19);

justify-content: center;}
.titleform{color: #3baea0;
padding: 20px 0 0 20px;}

</style>

<body>
    


<h1>Ajouter un médicament supplémentaire à la facture {{ facture.id }}</h1>
<div class="form">
<form method="POST">
    {% csrf_token %}

    

    <label for="medicament">Médicament:</label>
    <select name="medicament" id="medicament"required>
        <option value="">Choisir un médicament</option>
        {% for medicament in meds %}
        <option value="{{ medicament.id }}" data-qte="{{ medicament.qte }}">{{ medicament.designation }}</option>
        {% endfor %}
    </select>

    <br>

    <label for="quantite_stock">Quantité en stock:</label>
    <input type="number" name="quantite_stock" id="quantite_stock" readonly required>

    <br>

    <label for="quantite_demandee">Quantité demandée:</label>
    <input type="number" name="quantite_demandee" id="quantite_demandee"required min="1">
    <br>

    

    <button type="submit">Ajouter le médicament</button>
</form>

</div>


</body>

<script>
     // Récupérer les éléments HTML
     var selectMedicament = document.getElementById('medicament');
    var inputQteStock = document.getElementById('quantite_stock');
    var quantiteStockInput = inputQteStock;

    // Écouter l'événement de changement de sélection du médicament
    selectMedicament.addEventListener('change', function() {
        var selectedOption = selectMedicament.options[selectMedicament.selectedIndex];
        inputQteStock.value = selectedOption.getAttribute('data-qte');
    });
</script>


</html>

monprojet/templates/factures/creer_facture.html
{% load static%}

{% include 'parties/nav.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
       

    *{padding: 0;
    margin: 0;
box-sizing: border-box;
font-family: 'Poppins',sans-serif;}
body{
min-height: 100vh;
}
a{text-decoration: none;}


.container{
position: absolute;
right: 0;
width: 80vw;
height: 100vh;
background: #f1f1f1;
}




.btn{

background-color: #3baea0;
color: white;
padding: 5px 10px;
text-align: center;

}
.btn:hover{

color: #3baea0;
background: rgb(255, 255, 255);
padding: 3px 8px;
border: 2px solid #3baea0;

}
.container .content_2{
position: relative;
margin-top: 10vh;
min-height: 90vh;
background: #f1f1f1;
}

h3{color: #999;}
.container .content-2{
min-height: 60vh;
display: flex;
justify-content: space-around;
align-items: flex-start;
flex-wrap: wrap;
margin-top: 100px;
}


.container .content-2 .recent-payments{
    width: 700px;
background: white;
min-height: 50vh;
margin: 0 25px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;
height: 500px;
}
.container .content-2 .new-student{
min-height: 50vh;
flex: 2;
background: white;
margin: 0 25px 25px 25px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;

}

.title{
display: flex;
align-items: center;
justify-content: space-around;
padding: 15px 10px;
border-bottom: 2px solid #999;
}
table{
padding: 10px;
}
th,td{text-align: left;
padding: 8px;
}
.container  .content-2 .recent-students table td:nth-child(1) img {
width: 40px;
height: 40px;
}



@media screen and (max-width:940px) {

.container  .content-2 .recent-payments table th:nth-child(2),
.container  .content-2 .recent-payments table th:nth-child(2){ 
    display: none;
}

}

            /* Styles pour la forme */
            form {
                padding: 20px;
               
                
            }
        
            label {
                display: block;
                margin-bottom: 5px;
                font-size: 16px;
font-size: medium;            }
        
            select, input[type="text"], input[type="number"],input[type="date"], textarea {
                width: 253px;
                margin-bottom: 10px;
                padding: 7px;


               
            
            border: 1px solid #ccc;
            border-radius: 4px;
            }
        
            textarea {
                height: 50px;
            }
        
            button[type="submit"] {
                padding: 10px 20px;
                background-color: #3baea0;
                color: white;
                border: none;
                cursor: pointer;
                
               
            }
        
            /* Styles spécifiques aux éléments */
            #id_adresse_fournisseur,
            #id_qualite_fournisseur,
            #quantite_stock {
                background-color: #f2f2f2;
                cursor: not-allowed;
            }
          form .form1{display:inline;
            float: left;
           margin-right: 35px;
           border-right:2px solid #999;
           padding-right: 30px;
           
        }
        .titleform{color: #3baea0;
        padding: 20px 0 0 20px;}
        option{font-size: 18px;}
       
        </style>
         
           
        </style>
        

<body>
    

<div class="container">

    <div class="content-2">
     <div class="recent-payments">

      <h2 class="titleform">Creer une facture:</h2>
        <form method="POST">
            {% csrf_token %}
        <div class="form1">
            <label for="patient">Client:</label>
            <select name="patient" id="patient"required>
                <option value="">Choisir un client</option>
                {% for patient in pats %}
                <option value="{{ patient.id }}" data-adresse="{{ patient.adress }}" >{{ patient.nom }}</option>
                {% endfor %}
            </select>
        
          <p style="color: #999;">si le client n'pas encore enregistrer cliquer ici: </p>
          
          <a style="color: aqua;" href="{% url 'clients' %}">Ajouter client</a>
            <br>
    
          
            <br>
            <label for="id_date_facture">Date de facture:</label>
            <input  type="date" name="date_facture" id="id_date_facture" required>
        
           
            <br>
        </div>
        <div class="form2">
            <label for="medicament">Médicament:</label>
            <select name="medicament" id="medicament"required>
                <option value="">Choisir un médicament</option>
                {% for medicament in meds %}
                <option value="{{ medicament.id }}" data-prix="{{ medicament.prix_vente }}">{{ medicament.designation }}</option>
                {% endfor %}
            </select>
        
            <br>
        
            <label for="prix_vente">Prix de vente:</label>
            <input type="number" name="prix_vente" id="prix_vente" readonly required>
        
            <br>
        
            <label for="quantite_demandee">Quantité demandée:</label>
            <input type="number" name="quantite_demandee" id="quantite_demandee"required min="1">
            <br>
        
        </div>
        <div style="
        margin-top: 100px;
        text-align: center;">
            <button type="submit" class="btn">Enregistrer la facture</button>
        </div>
        </form>
        
  


     </div>
    
    </div>
</div>


<script>
    // Récupérer les éléments HTML
    var selectPatient = document.getElementById('patient');
    var inputAdressePatient = document.getElementById('id_adresse_patient');

    // Écouter l'événement de changement de sélection du fournisseur
    selectPatient.addEventListener('change', function() {
        var selectedOption = selectPatient.options[selectPatient.selectedIndex];
        inputAdressePatient.value = selectedOption.getAttribute('data-adresse');
    });

    // Récupérer les éléments HTML
    var selectMedicament = document.getElementById('medicament');
    var inputQteStock = document.getElementById('prix_vente');
    var quantiteStockInput = inputQteStock;

    // Écouter l'événement de changement de sélection du médicament
    selectMedicament.addEventListener('change', function() {
        var selectedOption = selectMedicament.options[selectMedicament.selectedIndex];
        inputQteStock.value = selectedOption.getAttribute('data-prix');
    });

   
       
</script>
</body>
</html>
{% endblock content %}

monprojet/templates/factures/imprimer_facture.html
<!DOCTYPE html>
<html>
<head>
    <title>Facture </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        .header {
          text-align: center;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            
        }

        .info {
text-align: left;
justify-content: left;  }
        .info-row {
            text-align: right;  
          justify-content: left;      }

        

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .table th, .table td {
            border: 1px solid #000;
            padding: 8px;
        }

        .table th {
            background-color: #f0f0f0;
        }

        .footer {
            text-align: center;
            justify-content: left;
            margin-top: 40px;
            font-size: 14px;
        }
        span {
            font-size: 14px;
        }
        .gr  {
            font-size: 17px;
            color: aquamarine;
        }
    </style>
</head>
<body>
    <div class="header">
     <span class="gr">  Informations sur la facture :</span><br>
     <span> Numéro de facture :</span> {{ facture.id }} <br>
     <span> Date de facture:</span> {{ facture.date_facture }} <br>
      
    </div>

    <div class="info">
    <span> Pharmacie ABC </span> <br>
      <span>  Adresse de la pharmacie</span> <br>
      <span>Téléphone :</span>  0654432112 <br>
      <span> Email : </span> info@pharmacie-ABC.com
      </div>

        <div class="info-row">
           
       <span>Client :</span>     {{ facture.patient }}<br>
       <span>Adress :</span>     {{ facture.patient.adress }}<br>
       <span>Téléphone :</span>  {{ facture.patient.tel }}<br>
        
        </div>

   
    <h2>Médicaments inclus :</h2>

    <table class="table">
      <thead>
        <tr>
          <th>Nom médicament</th>
          <th>Quantité demandée</th>
          <th>Prix de vente</th>
          <th>Prix total</th>
        </tr>
      </thead>
      <tbody>
        {% for medicament_facture in medicaments_facture %}
          <tr>
            <td>{{ medicament_facture.medicament.designation }}</td>
            <td>{{ medicament_facture.quantite_demandee }}</td>
            <td>{{ medicament_facture.medicament.prix_vente }}</td>
            <td>{{ medicament_facture.prix_total }}</td>
          </tr>
        {% endfor %}
    
        {% for medicament_facture in medicament_list %}
          <tr>
            <td>{{ medicament_facture.medicament.designation }}</td>
            <td>{{ medicament_facture.quantite_demandee }}</td>
            <td>{{ medicament_facture.medicament.prix_vente }}</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
<tfoot>
  <tr style="color: aqua;font-size: large;">
    <td colspan="3">Prix total</td>
    <td>{{ total_prix }}</td>
  </tr>
</tfoot>
</table>


    <div class="footer">
        <p>Merci d'avoir choisi Pharmacie ABC. Si vous avez des questions concernant cette commande, veuillez nous contacter aux coordonnées mentionnées ci-dessus.</p>
    </div>
    <p>Signature:</p>
</body>
</html>