monprojet/gcommande/urls.py
from django.urls import path
from . import views

    
urlpatterns = [
   path('creer_commande/',views.creer_commande, name='creer_commande'),
  path('afficher_commande/<int:commande_id>/',views.afficher_commande, name='afficher_commande'),
 path('commande/ajouter_medicament/<int:commande_id>/', views.ajouter_medicament, name='ajouter_medicament'),

   path('commande/imprimer/<int:commande_id>/', views.imprimer_commande, name='imprimer_commande'),

       path('tout_commandes/', views.tout_commandes, name='tout_commandes'),
           path('calcul_quantite_optimale', views.calcul_quantite_optimale, name='calcul_quantite_optimale'),


]
   

monprojet/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index, name = 'index'),
    path('menu', views.menu, name = 'menu'),


]

monprojet/monprojet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
     path('',include('gventes.urls')),
    path('',include('home.urls')),
    path('',include('gststock.urls')),
    path('',include('gfournisseur.urls')),
    path('',include('client.urls')),
    path('',include('utilisateur.urls')),
    path('',include('gcommande.urls')),
    path('',include('factures.urls')),





]

monprojet/gcommande/models.py
from datetime import date
from django.db import models
from gfournisseur.models import fournisseur
from gststock.models import medicament


class gcommandes(models.Model):
    fournisseur = models.ForeignKey(fournisseur, on_delete=models.CASCADE, null=True)
  
    adresse_livraison = models.TextField()
    date_commande =models.DateField(default= date.today)
    imprimee = models.BooleanField(default=False)
    annulee = models.BooleanField(default=False)


    def __str__(self):
        return f"Commande #{self.id}"


class MedicamentsCommande(models.Model):
    commande = models.ForeignKey(gcommandes, on_delete=models.CASCADE,null=True)
    medicament = models.ForeignKey(medicament, on_delete=models.CASCADE,null=True)
    quantite_demandee = models.IntegerField()
    description = models.TextField()
    D = models.FloatField(default=0.0)  # Demande annuelle prévue
    S = models.FloatField(default=0.0)  # Coût unitaire de possession de stock
    C = models.FloatField(default=0.0)  # Coût de commande


    def __str__(self):
        return f"MedicamentCommande #{self.id}"

monprojet/gcommande/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .models import medicament, gcommandes, MedicamentsCommande,fournisseur
from django.db.models import F


def is_gerant(user):
    return user.profile.grade == 'gerant'

@login_required
@user_passes_test(is_gerant)
def creer_commande(request):

    frns = fournisseur.objects.all()
    meds = medicament.objects.all()

    if request.method == 'POST':
        fournisseur_id = request.POST.get('fournisseur')
        adresse_livraison = request.POST.get('adresse_livraison')
        date_commande= request.POST.get('date_commande')


        fourniseur = fournisseur.objects.get(pk=fournisseur_id)
        commande = gcommandes.objects.create(fournisseur=fourniseur, adresse_livraison=adresse_livraison,date_commande=date_commande)

        medicament_id = request.POST.get('medicament')
        quantite_stock = medicament.objects.get(pk=medicament_id).qte
        quantite_demandee = int(request.POST.get('quantite_demandee'))
        description = request.POST.get('description')

        medicament_commande = MedicamentsCommande.objects.create(commande=commande,
                                                                medicament_id=medicament_id,
                                                                quantite_demandee=quantite_demandee,
                                                                description=description)

        index = 1
        medicament_list = []  # Liste pour stocker les informations des médicaments supplémentaires
           
         #  
        while True:
            medicament_id = request.POST.get(f'medicament_{index}')

            if not medicament_id:
                break

            quantite_demandee = int(request.POST.get(f'quantite_demandee_{index}'))
            description = request.POST.get(f'description_{index}')
            medicaments = medicament.objects.get(pk=medicament_id)

            medicament_commande = MedicamentsCommande.objects.create(commande=commande,
                                                            medicaments=medicaments,
                                                            quantite_demandee=quantite_demandee,
                                                            description=description)

            medicament_list.append(medicament_commande)  # Ajouter l'objet MedicamentCommande à la liste


           
           
           
           
         #  
            index += 1

        return redirect('afficher_commande', commande_id=commande.id)
    medicaments_rupture = medicament.objects.filter(qte__lte=F('stock_min'))

    return render(request, 'gcommande/creer_commande.html', { 'meds': meds,'frns':frns,
                                                             'medicaments_rupture':medicaments_rupture})
@user_passes_test(is_gerant)

def afficher_commande(request, commande_id):
    commande = gcommandes.objects.get(pk=commande_id)
    medicaments_commande = MedicamentsCommande.objects.filter(commande=commande)
    medicament_list = []  # Liste pour stocker les médicaments supplémentaires

    # Récupérer les informations des médicaments supplémentaires
    medicament_commandes_supplementaires = MedicamentsCommande.objects.filter(commande=commande).exclude(id__in=medicaments_commande.values_list('id', flat=True))
    
    for medicament_commande in medicament_commandes_supplementaires:
        medicament = medicament_commande.medicament
        quantite_demandee = medicament_commande.quantite_demandee
        description = medicament_commande.description

        medicament_info = {
            'medicament': medicament,
            'quantite_demandee': quantite_demandee,
            'description': description
        }
        medicament_list.append(medicament_info)
        #
        
        # annuler commande
    commande = gcommandes.objects.get(pk=commande_id)
    
    if request.method == 'POST' and 'annuler_commande' in request.POST:
        commande.annulee = True
        commande.save()
        return redirect('afficher_commande', commande_id=commande.id)
    

#


    return render(request, 'gcommande/afficher_commande.html', {'commande': commande,
                                                                'medicaments_commande': medicaments_commande,
                                                                'medicament_list': medicament_list})


@user_passes_test(is_gerant)

def ajouter_medicament(request, commande_id):
    commande = gcommandes.objects.get(pk=commande_id)
    medicaments_commande = MedicamentsCommande.objects.filter(commande=commande)

    if request.method == 'POST':
        medicament_id = request.POST.get('medicament')
        quantite_stock = medicament.objects.get(pk=medicament_id).qte
        quantite_demandee = int(request.POST.get('quantite_demandee'))
        description = request.POST.get('description')

        medicament_commande = MedicamentsCommande.objects.create(commande=commande,
                                                                medicament_id=medicament_id,
                                                                quantite_demandee=quantite_demandee,
                                                                description=description)

        return redirect('afficher_commande', commande_id=commande.id)

    meds = medicament.objects.all()
    return render(request, 'gcommande/ajouter_medicament.html', {'commande': commande, 'meds': meds})

from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa
from io import BytesIO

@user_passes_test(is_gerant)

def imprimer_commande(request, commande_id):
    commande = gcommandes.objects.get(pk=commande_id)

    # Récupérez les informations nécessaires pour générer le contenu de l'impression
    context = {
        'commande': commande,
        'medicaments_commande': MedicamentsCommande.objects.filter(commande=commande),
        'medicament_list': MedicamentsCommande.objects.filter(commande=commande).exclude(id__in=MedicamentsCommande.objects.filter(commande=commande).values_list('id', flat=True))
    }

    # Chargez le template d'impression
    template = get_template('gcommande/imprimer_commande.html')
    content = template.render(context)

    # Créez un flux de données pour stocker le résultat PDF
    pdf_file = BytesIO()

    # Convertissez le contenu HTML en PDF
    pisa.CreatePDF(content, dest=pdf_file)

    # Récupérez le contenu du fichier PDF à partir du flux de données
    pdf = pdf_file.getvalue()

    # Fermez le flux de données
    pdf_file.close()

    # Créez une réponse HTTP avec le contenu du PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="commande.pdf"'

    # Écrivez le contenu PDF dans la réponse HTTP
    response.write(pdf)

    return response


def tout_commandes(request):
 cmd =gcommandes.objects.all().filter(annulee='False')
       
 context = {'cmd': cmd}
 return render(request, 'gcommande/tout_commandes.html',context)
 

from math import sqrt

def calcul_quantite_optimale(request):
    if request.method == 'POST':
        demande_annuelle = float(request.POST['demande_annuelle'])
        cout_stock = float(request.POST['cout_stock'])
        cout_commande = float(request.POST['cout_commande'])

        quantite_optimale = round(sqrt((2 * demande_annuelle * cout_commande) / cout_stock))

        return render(request, 'resultat_quantite_optimale.html', {'quantite_optimale': quantite_optimale})

    return render(request, 'calcul_quantite_optimale.html')

monprojet/templates/gcommande/afficher_commande.html
{% load static%}

{% include 'parties/nav.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
       
 p span{color: #3baea0;
 font-size: large;
}
    *{padding: 0;
    margin: 0;
box-sizing: border-box;
font-family: 'Poppins',sans-serif;}
body{
min-height: 100vh;
}
a{text-decoration: none;}
li{list-style: none;}

h1,h2{color: #444;}


.container{
position: absolute;
right: 0;
width: 80vw;
height: 100vh;
background: #f1f1f1;
}
.container .header{
position: fixed;
top: 0;
right: 0;
width: 80vw;
height: 10vh;
background: white;
display: flex;
align-items: center;
justify-content: center;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
z-index: 1;

}
.container .header .nav{width: 90%;
display: flex;
align-items: center;
}
.container .header .nav .search{
flex: 3;
display: flex;
justify-content: center;
}
.container .header .nav .search button{
width: 40px;
height: 40px;
border: none;
display: flex;
align-items: center;
justify-content: center;}
.container .header .nav .search button img{
width: 30px;
height: 30px;
}



.container .header .nav .user .img-case {
position: relative; 
width: 50px;
height: 50px;
}
.container .header .nav .user .img-case img{
position: absolute; 
top: 0;
left: 0;
width: 100%;

}
.btn{

background-color: #3baea0;
color: white;
padding: 5px 10px;
text-align: center;

}
.btn:hover{

color: #3baea0;
background: rgb(255, 255, 255);
padding: 3px 8px;
border: 2px solid #3baea0;

}
.container .content{
position: relative;
margin-top: 10vh;
min-height: 90vh;
background: #f1f1f1;
}
.container .content .cards{
padding: 10px 15px;
display: flex;
align-items: center;
justify-content: space-between;
flex-wrap: wrap;
justify-content: center;}
.container .content .cards .card{
width: 800px;
height: 150px;
background: white;
display: flex;
justify-content: space-around;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
text-align: center;
}
.annuler{margin-top: 5px;
  margin-bottom: 5px;
}
 .card2{
width: 300px;
height: 50px;
background: white;
margin: 0px 10px ;
display: flex;
align-items: center;
justify-content: space-around;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
font-size: 18px;
color: #3baea0;
border: 2px solid #3baea0;}
h3{color: #999;}
.container .content .content-2{
min-height: 60vh;
display: flex;
justify-content: space-around;
align-items: flex-start;
flex-wrap: wrap;
}
.container .content .content-2 .recent-payments{
min-height: 40vh;
width: 800px;
background: white;
margin: 0 25px 0px 25px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;
}




.title{
display: flex;
align-items: center;
justify-content: space-around;
padding: 15px 10px;
border-bottom: 2px solid #999;
}
.side-menu li img{width: 30px;height: 30px;}
table{
padding: 10px;
}
th,td{text-align: left;
padding: 8px;
}
.container .content .content-2 .recent-students table td:nth-child(1) img {
width: 40px;
height: 40px;
}

.commande h1{color: lightcoral;
padding: 10px 0 0 0px;
text-align: center;
}
.pc {background: lightcoral;
padding: 10px;}
.annuler{display: flex;
justify-content: center;}
@media screen and (max-width:536px) {

.container .content .cards {
justify-content: center;}}
</style>
</head>
<body>
  <div class="container">
    
<div class="content">
  <div class="commande">
  <h1>Commande Num: {{ commande.id }}</h1>
</div>
    <div class="cards">

        <div class="card">
            <div class="box">
             
              <div class="title">
              <h2>Informations sur la commande :</h2>
            </div>
            <br>
              <p><span> Fournisseur :</span> {{ commande.fournisseur }}</p>
              <p><span>Adresse de livraison :</span> {{ commande.adresse_livraison }}</p>
              <p><span>Date de commande:</span> {{ commande.date_commande }}</p>
              
            </div>
           
        </div>

       
     

    </div>
        <div class="content-2">
<div class="recent-payments">
    <div class="title">
      <h2>Médicaments inclus :</h2>

        <a href="{% url 'ajouter_medicament' commande_id=commande.id %}" class="btn">Ajouter medicament</a>
        
    </div>
    <table>
      <thead>
        <tr>
          <th>Médicament</th>
          <th>Quantité demandée</th>
          <th>Forme</th>
          <th>Description</th>
          
        </tr>
      </thead>
      <tbody>
        {% for medicament_commande in medicaments_commande %}
          <tr>
            <td>{{ medicament_commande.medicament.designation }}</td>
            <td>{{ medicament_commande.quantite_demandee }}</td>
            <td>{{ medicament_commande.medicament.forme }}</td>
            <td>{{ medicament_commande.description }}</td>
          </tr>
        {% endfor %}
    
        {% for medicament_commande in medicament_list %}
          <tr>
            <td>{{ medicament_commande.medicament.designation }}</td>
            <td>{{ medicament_commande.quantite_demandee }}</td>
            <td></td>
            <td>{{ medicament_commande.description }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>



<div class="annuler">
 
<a class="card2" href="{% url 'imprimer_commande' commande_id=commande.id %}" target="_blank">Imprimer</a>



  {% if not commande.annulee %}
        <form method="post" action="">
            {% csrf_token %}
            <button class="card2" type="submit" name="annuler_commande">Annuler la commande</button>
        </form>
  {% else %}
        <p>La commande a été annulée.</p>
  {% endif %}

</div>  
  </div>
 
</div>



 </div> 
 







</body>
</html>
{% endblock content %}

monprojet/templates/gcommande/ajouter_medicament.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style> form {
    padding: 20px; 
}
h1{color: white;
}
body {
  background: linear-gradient(45deg, #ccc 0%, #ccc 50%, #3baea0 50%, #3baea0 100%);
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
}

label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

select, input[type="text"], input[type="number"],input[type="date"], textarea {
    width: 300px;
    margin-bottom: 10px;
    padding: 10px;


   

border: 1px solid #ccc;
border-radius: 4px;
}

option {font-size: 18px;}
textarea {
    height: 50px;
}

button[type="submit"],[type="button"] {
    padding: 10px 20px;
    background-color: #3baea0;
    color: white;
    border: none;
    cursor: pointer;
    
   
}form

/* Styles spécifiques aux éléments */
#id_adresse_fournisseur,
#id_qualite_fournisseur,
#quantite_stock {
    background-color: #f2f2f2;
    cursor: not-allowed;
}
#resultat_quantite_optimale{
                text-align: center;
                color: red;
             }
.form ,h1 {display: flex;justify-content: center;}
form {display:inline;
float: left;
margin-right: 2px;
padding-right: 30px;
border: 1px solid #ccc;
            border-radius: 5px;
            background:white;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.19);

justify-content: center;}
.titleform{color: #3baea0;
padding: 20px 0 0 20px;}

</style>

<body>
    


<h1>Ajouter un médicament supplémentaire à la commande {{ commande.id }}</h1>
<div class="form">
<form method="POST">
    {% csrf_token %}

    

    <label for="medicament">Médicament:</label>
    <select name="medicament" id="medicament"required>
        <option value="">Choisir un médicament</option>
        {% for medicament in meds %}
        <option value="{{ medicament.id }}" data-qte="{{ medicament.qte }}">{{ medicament.designation }}</option>
        {% endfor %}
    </select>

    <br>

    <label for="quantite_stock">Quantité en stock:</label>
    <input type="number" name="quantite_stock" id="quantite_stock" readonly required>

    <br>

    <label for="quantite_demandee">Quantité demandée:</label>
    <input type="number" name="quantite_demandee" id="quantite_demandee"required min="1">
    <br>

    <label for="description">Description:</label>
    <textarea name="description" id="description"required></textarea>
    <br>

    <button type="submit">Ajouter le médicament</button>




    
</form>

    <form >
        <h2 style="color: #ccc;">Calcul de la quantité optimale</h2>

        <label for="demande_annuelle">Demande annuelle prévue:</label>
        <input type="number" id="demande_annuelle" required>

        <br>

        <label for="cout_stock">Coût unitaire de possession de stock:</label>
        <input type="number" id="cout_stock" required>

        <br>

        <label for="cout_commande">Coût de commande:</label>
        <input type="number" id="cout_commande" required>

        <br>

        <button  type="button" onclick="calculerQuantiteOptimale()">Calculer</button>
        <div id="resultat_quantite_optimale"></div>
    </form>


</div>


</body>

<script>
     // Récupérer les éléments HTML
     var selectMedicament = document.getElementById('medicament');
    var inputQteStock = document.getElementById('quantite_stock');
    var quantiteStockInput = inputQteStock;

    // Écouter l'événement de changement de sélection du médicament
    selectMedicament.addEventListener('change', function() {
        var selectedOption = selectMedicament.options[selectMedicament.selectedIndex];
        inputQteStock.value = selectedOption.getAttribute('data-qte');
    });
</script>

<script>
    function calculerQuantiteOptimale() {
        var demandeAnnuelle = parseFloat(document.getElementById('demande_annuelle').value);
        var coutStock = parseFloat(document.getElementById('cout_stock').value);
        var coutCommande = parseFloat(document.getElementById('cout_commande').value);

        var quantiteOptimale = Math.round(Math.sqrt((2 * demandeAnnuelle * coutCommande) / coutStock));

        document.getElementById('resultat_quantite_optimale').innerHTML = "La quantité optimale est : " + quantiteOptimale;
    }
</script>
</html>



    
   

monprojet/templates/gcommande/creer_commande.html
{% load static%}

{% include 'parties/nav.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
       

    *{padding: 0;
    margin: 0;
box-sizing: border-box;
font-family: 'Poppins',sans-serif;}
body{
min-height: 100vh;
}
a{text-decoration: none;}


.container{
position: absolute;
right: 0;
width: 80vw;
background: #f1f1f1;
}




.btn{

background-color: #3baea0;
color: white;
padding: 5px 10px;
text-align: center;

}
.btn:hover{

color: #3baea0;
background: rgb(255, 255, 255);
padding: 3px 8px;
border: 2px solid #3baea0;

}
.container .content_2{
position: relative;
margin-top: 10vh;
min-height: 90vh;
background: #f1f1f1;
}

h3{color: #999;}
.container .content-2{
min-height: 60vh;
display: flex;
justify-content: space-around;
align-items: flex-start;
flex-wrap: wrap;
margin-top: 85px;
}


.container .content-2 .recent-payments{
flex: 5;
background: white;
min-height: 50vh;
margin: 0 15px 0px 25px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;
height: 525px;
}
.container .content-2 .new-student{
flex: 3;
background: white;
margin: 0 15px 5px 5px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
display: flex;
flex-direction: column;
height:242px ;

}


.container .content-2 .qte_optimal{
background: white;
margin: 0 15px 5px 5px;
box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
flex-direction: column;

}

.title{
display: flex;
align-items: center;
justify-content: space-around;
padding: 15px 10px;
border-bottom: 2px solid #999;
}
table{
padding: 10px;
}
th,td{text-align: left;
padding: 8px;
}
.container  .content-2 .recent-students table td:nth-child(1) img {
width: 40px;
height: 40px;
}

.table-container1 {
        
    overflow: auto; 
     
    
      }

@media screen and (max-width:940px) {

.container  .content-2 .recent-payments table th:nth-child(2),
.container  .content-2 .recent-payments table th:nth-child(2){ 
    display: none;
}

}

            /* Styles pour la forme */
            form {
                padding: 20px;
               
                
            }
            #resultat_quantite_optimale{
                text-align: center;
                color: red;
             }
        
            label {
                display: block;
                margin-bottom: 5px;
                font-size: 16px;
font-size: medium;            }
        
            select, input[type="text"], input[type="number"],input[type="date"], textarea {
                width: 253px;
                margin-bottom: 10px;
                padding: 7px;


               
            
            border: 1px solid #ccc;
            border-radius: 4px;
            }
        
            textarea {
                height: 50px;
            }
        
            button[type="submit"] {
                padding: 10px 20px;
                background-color: #3baea0;
                color: white;
                border: none;
                cursor: pointer;
                
               
            }
        
            /* Styles spécifiques aux éléments */
            #id_adresse_fournisseur,
            #id_qualite_fournisseur,
            #quantite_stock {
                background-color: #f2f2f2;
                cursor: not-allowed;
            }
          form .form1{display:inline;
            float: left;
           margin-right: 35px;
           border-right:2px solid #999;
           padding-right: 30px;
           
        }
        .titleform{color: #3baea0;
        padding: 20px 0 0 20px;}
        option{font-size: 18px;}
       
        </style>
         
           
        </style>
        

<body>
    

<div class="container">

    <div class="content-2">
     <div class="recent-payments">

      <h2 class="titleform">Creer une commande:</h2>
        <form method="POST">
            {% csrf_token %}
        <div class="form1">
            <label for="fournisseur">Fournisseur:</label>
            <select name="fournisseur" id="fournisseur"required>
                <option value="">Choisir un fournisseur</option>
                {% for fournisseur in frns %}
                <option value="{{ fournisseur.id }}" data-adresse="{{ fournisseur.adress }}" data-qualite="{{ fournisseur.qualite }}">{{ fournisseur.nom }}</option>
                {% endfor %}
            </select>
        
            <br>
            <label for="id_adresse_fournisseur">Adresse du fournisseur:</label>
            <input type="text" name="adresse_fournisseur" id="id_adresse_fournisseur" readonly required>
        
            <br>
        
            <label for="id_qualite_fournisseur">Qualité de service du fournisseur:</label>
            <input type="text" name="qualite_fournisseur" id="id_qualite_fournisseur" readonly required>
        
            <br>
            <label for="adresse_livraison">Adresse de livraison:</label>
            <textarea name="adresse_livraison" id="adresse_livraison" required></textarea>
            
            <br>
            <label for="id_date_commande">Date de commande:</label>
            <input  type="date" name="date_commande" id="id_date_commande" required>
        
           
            <br>
        </div>
        <div class="form2">
            <label for="medicament">Médicament:</label>
            <select name="medicament" id="medicament"required>
                <option value="">Choisir un médicament</option>
                {% for medicament in meds %}
                <option value="{{ medicament.id }}" data-qte="{{ medicament.qte }}">{{ medicament.designation }}</option>
                {% endfor %}
            </select>
        
            <br>
        
            <label for="quantite_stock">Quantité en stock:</label>
            <input type="number" name="quantite_stock" id="quantite_stock" readonly required>
        
            <br>
        
            <label for="quantite_demandee">Quantité demandée:</label>
            <input type="number" name="quantite_demandee" id="quantite_demandee"required min="1">
            
            <br>
        
            <label for="description">Description:</label>
            <textarea name="description" id="description"required></textarea>
            <br>





            
        </div>
        <div style="
        margin-top: 100px;
        text-align: center;">
            <button type="submit" class="btn">Enregistrer la commande</button>
        </div>
        </form>
        
  


     </div>
     <div class="block_2">

        <div class="qte_optimal">
    
            <h2 style="padding: 10px 0 0 10px;">Calcul de la quantité optimale</h2>
        
            <form style="padding: 10px;">
                <label for="demande_annuelle">Demande annuelle prévue:</label>
                <input type="number" id="demande_annuelle" required>
        
                <br>
        
                <label for="cout_stock">Coût unitaire de possession de stock:</label>
                <input type="number" id="cout_stock" required>
        
                <br>
        
                <label for="cout_commande">Coût de commande:</label>
                <input type="number" id="cout_commande" required>
        
                <br>
        
                <button class="btn" type="button" onclick="calculerQuantiteOptimale()">Calculer</button>
                <div id="resultat_quantite_optimale"></div>
            </form>
        
           
        
           </div>
     <div class="new-student">
    <div class="title">
        <h2>medicaments en rupture</h2>
    </div>
    
      <div class="table-container1">
    <table>
        <tr>
            <th>designation</th>
            <th>quantité en stock</th>
            <th>forme</th>
            
        </tr>
        {% for x in  medicaments_rupture %}
       
        <tr>
            <td>{{x.designation}} </td>
            <td>{{x.qte}}</td>
            <td>{{x.forme}}</td>
        </tr>
        {% endfor  %}

    </table>
</div>
     </div>


    

    </div>






    </div>
</div>


<script>
    // Récupérer les éléments HTML
    var selectFournisseur = document.getElementById('fournisseur');
    var inputAdresseFournisseur = document.getElementById('id_adresse_fournisseur');
    var inputQualiteFournisseur = document.getElementById('id_qualite_fournisseur');

    // Écouter l'événement de changement de sélection du fournisseur
    selectFournisseur.addEventListener('change', function() {
        var selectedOption = selectFournisseur.options[selectFournisseur.selectedIndex];
        inputAdresseFournisseur.value = selectedOption.getAttribute('data-adresse');
        inputQualiteFournisseur.value = selectedOption.getAttribute('data-qualite');
    });

    // Récupérer les éléments HTML
    var selectMedicament = document.getElementById('medicament');
    var inputQteStock = document.getElementById('quantite_stock');
    var quantiteStockInput = inputQteStock;

    // Écouter l'événement de changement de sélection du médicament
    selectMedicament.addEventListener('change', function() {
        var selectedOption = selectMedicament.options[selectMedicament.selectedIndex];
        inputQteStock.value = selectedOption.getAttribute('data-qte');
    });

   
       
</script>

<script>
    function calculerQuantiteOptimale() {
        var demandeAnnuelle = parseFloat(document.getElementById('demande_annuelle').value);
        var coutStock = parseFloat(document.getElementById('cout_stock').value);
        var coutCommande = parseFloat(document.getElementById('cout_commande').value);

        var quantiteOptimale = Math.round(Math.sqrt((2 * demandeAnnuelle * coutCommande) / coutStock));

        document.getElementById('resultat_quantite_optimale').innerHTML = "La quantité optimale est : " + quantiteOptimale;
    }
</script>
</body>
</html>
{% endblock content %}